"
" GVIMRC - for GUI Vim Version (gvim, MacVim)
"
" $Id$
set guifont=Monaco:h13
set anti
set lines=50
set columns=132
set mousefocus
set errorbells
set visualbell
set showtabline=2
set guicursor=a:blinkon0
set fuoptions=maxvert,maxhorz

set guioptions-=T
set guioptions+=a
if &background == "dark"
    hi normal guibg=black
    set transp=8
endif

"colorscheme zenburn
"colorscheme freya
"colorscheme moria
"colorscheme morning
"colorscheme desert
"colorscheme macvim
colorscheme inkpot

" Emacs like indenting. Pressing Tab indents line
" set indentkeys=0{,0},0),:,0#,!^F,o,O,e,!<Tab>,!^F
" set cinkeys=0{,0},0),:,0#,!^F,o,O,e,!<Tab>,!^F
